RAD301-Mock-Exam-2023-MVC-App-ppowell/Models/ErrorViewModel.cs
namespace RAD301_Mock_Exam_2023_MVC_App_ppowell.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RAD301-Mock-Exam-2023-MVC-App-ppowell/Controllers/CheckedInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rad301_Mock_Exam_2023_DataModel_ppowell;
using Tracker.WebAPIClient;

namespace RAD301_Mock_Exam_2023_MVC_App_ppowell.Controllers
{
    public class CheckedInController : Controller
    {
        private readonly FlightContext _context;

        public CheckedInController(FlightContext context)
        {
            _context = context;

            ActivityAPIClient.Track(
                StudentID: "ppowell",
                StudentName: "Paul Powell",
                activityName: "Rad301 Mock Exam 2023",
                Task: "Creating Checkin Controller");
        }

        // GET: CheckedIn
        public async Task<IActionResult> Index()
        {
              return _context.Flights != null ? 
                          View(await _context.Flights.ToListAsync()) :
                          Problem("Entity set 'FlightContext.Flights'  is null.");
        }

        // GET: CheckedIn/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Flights == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .Include(f => f.Passengers)
                .FirstOrDefaultAsync(m => m.FlightId == id);

            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: CheckedIn/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CheckedIn/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FlightId,FlightNumber,DepartureDate,Origin,Destination,Country,MaxSeats")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: CheckedIn/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Flights == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST: CheckedIn/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FlightId,FlightNumber,DepartureDate,Origin,Destination,Country,MaxSeats")] Flight flight)
        {
            if (id != flight.FlightId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.FlightId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: CheckedIn/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Flights == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .FirstOrDefaultAsync(m => m.FlightId == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: CheckedIn/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Flights == null)
            {
                return Problem("Entity set 'FlightContext.Flights'  is null.");
            }
            var flight = await _context.Flights.FindAsync(id);
            if (flight != null)
            {
                _context.Flights.Remove(flight);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightExists(int id)
        {
          return (_context.Flights?.Any(e => e.FlightId == id)).GetValueOrDefault();
        }
    }
}

RAD301-Mock-Exam-2023-MVC-App-ppowell/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RAD301_Mock_Exam_2023_MVC_App_ppowell.Models;
using System.Diagnostics;

namespace RAD301_Mock_Exam_2023_MVC_App_ppowell.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RAD301-Mock-Exam-2023-MVC-App-ppowell/Views/CheckedIn/Create.cshtml
@model Rad301_Mock_Exam_2023_DataModel_ppowell.Flight

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FlightNumber" class="control-label"></label>
                <input asp-for="FlightNumber" class="form-control" />
                <span asp-validation-for="FlightNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDate" class="control-label"></label>
                <input asp-for="DepartureDate" class="form-control" />
                <span asp-validation-for="DepartureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxSeats" class="control-label"></label>
                <input asp-for="MaxSeats" class="form-control" />
                <span asp-validation-for="MaxSeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RAD301-Mock-Exam-2023-MVC-App-ppowell/Views/CheckedIn/Delete.cshtml
@model Rad301_Mock_Exam_2023_DataModel_ppowell.Flight

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxSeats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxSeats)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlightId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RAD301-Mock-Exam-2023-MVC-App-ppowell/Views/CheckedIn/Details.cshtml
@model Rad301_Mock_Exam_2023_DataModel_ppowell.Flight

@{
    ViewData["Title"] = "Details";
}

<h1>Flight Details with Passangers</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxSeats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxSeats)
        </dd>
    </dl>
</div>
<div id="passengerDetailsContainer">
    @await Html.PartialAsync("_PassengerDetails", Model.Passengers)
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model?.FlightId">Edit</a> | *@
    <a class="btn btn-dark" asp-action="Index">Back to List</a>
</div>

RAD301-Mock-Exam-2023-MVC-App-ppowell/Views/CheckedIn/Edit.cshtml
@model Rad301_Mock_Exam_2023_DataModel_ppowell.Flight

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FlightId" />
            <div class="form-group">
                <label asp-for="FlightNumber" class="control-label"></label>
                <input asp-for="FlightNumber" class="form-control" />
                <span asp-validation-for="FlightNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDate" class="control-label"></label>
                <input asp-for="DepartureDate" class="form-control" />
                <span asp-validation-for="DepartureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxSeats" class="control-label"></label>
                <input asp-for="MaxSeats" class="form-control" />
                <span asp-validation-for="MaxSeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RAD301-Mock-Exam-2023-MVC-App-ppowell/Views/CheckedIn/Index.cshtml
@model IEnumerable<Rad301_Mock_Exam_2023_DataModel_ppowell.Flight>

@{
    ViewData["Title"] = "Index";
}

<h1>Index Detail Command Button shows Partial View</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FlightNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxSeats)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FlightNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Origin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxSeats)
            </td>
            <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.FlightId">Edit</a> |
                    <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.FlightId">Details</a> |
                    <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.FlightId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RAD301-Mock-Exam-2023-MVC-App-ppowell/Views/CheckedIn/_PassengerDetails.cshtml
@model IEnumerable<Rad301_Mock_Exam_2023_DataModel_ppowell.Passenger>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TicketType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TicketPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BaggageCharge)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Flight.Country)
            </th>
            <th>@Html.DisplayNameFor(model => model.Flight.FlightNumber)</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BaggageCharge)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Flight.Country)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Flight.FlightNumber)
                </td>
            @* <td>
                <a asp-action="Edit" asp-route-id="@item.PassengerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PassengerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PassengerId">Delete</a>
            </td> *@
        </tr>
}
    </tbody>
</table>

RAD301-Mock-Exam-2023-MVC-App-ppowell/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RAD301-Mock-Exam-2023-MVC-App-ppowell/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RAD301_Mock_Exam_2023_MVC_App_ppowell</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RAD301_Mock_Exam_2023_MVC_App_ppowell.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RAD301_Mock_Exam_2023_MVC_App_ppowell</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CheckedIn" asp-action="Index">Checked In</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RAD301_Mock_Exam_2023_MVC_App_ppowell - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>